services:
  kavita:
    image: jvmilazz0/kavita:0.9.0.2
    environment:
      - TZ=${TZ}
    networks:
      - default
      - proxy-network
    expose:
      - 5000
    volumes:
      - ./books:/books
      - ./manga:/manga
      - ./config:/kavita/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kavita.rule=Host(`${KAVITA_DOMAIN}`)"

networks:
  default:
  proxy-network:
    external: true

